@startuml

[eden-demo-cola-start（启动入口）] --> [eden-demo-cola-adapter（适配层）]
[eden-demo-cola-adapter（适配层）] --> [eden-demo-cola-app（应用层）]: 入站适配，数据组装
[eden-demo-cola-app（应用层）] --> [eden-demo-cola-client（API层）]: 实现接口
[eden-demo-cola-app（应用层）] --> [eden-demo-cola-domain（领域层）]: CQRS 增删改命令
[eden-demo-cola-app（应用层）] --> [eden-demo-cola-infrastructure（基础设施层）]: CQRS 查询视图
[eden-demo-cola-infrastructure（基础设施层）] --> [eden-demo-cola-domain（领域层）]: 依赖倒置

cloud APP
cloud 其他应用服务
cloud 第三方接口
cloud 分布式调度平台

database MySQL
database Redis
database MQ
database Elasticsearch
database MongoDB

http - [eden-demo-cola-adapter（适配层）]: REST 接口
[APP] ..> http: 前后端对接

[eden-demo-cola-adapter（适配层）] - rpc: Dubbo 接口
[其他应用服务] ..> rpc: 网络调用
[其他应用服务] ..> [eden-demo-cola-client（API层）]: 代码集成

[eden-demo-cola-adapter（适配层）] ..> MQ: 消费消息
[分布式调度平台] ..> [eden-demo-cola-adapter（适配层）]: 触发任务

[eden-demo-cola-infrastructure（基础设施层）] ..> MySQL: 读写数据
[eden-demo-cola-infrastructure（基础设施层）] ..> Elasticsearch: 读写索引
[eden-demo-cola-infrastructure（基础设施层）] ..> MongoDB: 读写数据
[eden-demo-cola-infrastructure（基础设施层）] ..> MQ: 生产消息
[eden-demo-cola-infrastructure（基础设施层）] ..> Redis: 读写缓存
[eden-demo-cola-infrastructure（基础设施层）] ..> 第三方接口: 接口调用

@enduml
